repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff  # Linter
        args: [--fix]  # Upewnij się, że poprawki są stosowane automatycznie
      - id: ruff-format  # Formatter
